### PR TITLE
Add SymEngine, GiNaC and Mathematica benchmarks

### PR DESCRIPTION
**Pull request by isuruf**
image

image

image

### CODE REVIEW

**Comment by isuruf** [comment]
Added SymPy benchmarks as well

**Comment by certik** [comment]
@isuruf thank you, this is exactly what I was looking for. We should also add instructions how to generate the `data.json` file (be we should still keep `data.json` in git).

Feel free to merge any time.

**Comment by isuruf** [comment]
I have updated the PR with Maple benchmarks

**Comment by certik** [comment]
I think Maple is probably using polynomials, not symbolics. Try some
benchmark that cannot be done using polynomials.

**Comment by isuruf** [comment]
Do you have any benchmark in mind?

**Comment by certik** [comment]
Try the one with (x^y+y^z+z^x)^n, we already have it, just don't remember
the number. Otherwise try to design one. Perhaps take expand2, but put
there functions like sin(x) or more complicated expressions than just
symbols.

**Comment by isuruf** [comment]
`(x**y + y**x + z**x + sin(x)) ^ n` seems to trigger symbolic expansion. Shall I replace `(x^y+y^z+z^x)^n` with this?

**Comment by certik** [comment]
No, do not replace, just put it in addition.

Also we should put our polynomial benchmarks, probably using Piranha. To show that we can match Maple, when we compare apples to apples.

**Comment by isuruf** [comment]
One difference between symengine and others is that symengine automatically expands `(x**y)**2` to `x**(2*y)` while others do not

**Comment by certik** [comment]
@isuruf right. Can we force the others to do this simplification as well? If not, let's design some other benchmark that doesn't have nested powers.

**Comment by isuruf** [comment]
I don't think so.
How about we change `expand6` to `a0 + a1 + sin(a2) + sin(a3) + ... +` (call it `expand6b`) ?
`expand6` is a benchmark from GiNaC

**Comment by certik** [comment]
Sounds good.

**Pull request merged**
